# Generated by Django 3.2.6 on 2022-07-03 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cancelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre:')),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('phone', models.CharField(max_length=15, verbose_name='Número de teléfono:')),
                ('order', models.CharField(max_length=255, verbose_name='Orden:')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
