# Generated by Django 3.2.6 on 2022-07-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_remove_cancelrequest_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='messagesContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto:')),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('message', models.CharField(max_length=255, verbose_name='Mensaje:')),
            ],
        ),
    ]
