# Generated by Django 3.2.6 on 2022-07-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_cancelrequest_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelrequest',
            name='status',
            field=models.CharField(default='Pedido ingresado', max_length=25, verbose_name='Estado:'),
        ),
    ]
