# Generated by Django 3.2.6 on 2022-07-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_auto_20220705_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancelrequest',
            options={'verbose_name': 'Pedido de cancelación', 'verbose_name_plural': 'Pedidos de cancelación'},
        ),
        migrations.AlterModelOptions(
            name='messagescontactus',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterField(
            model_name='cancelrequest',
            name='employee',
            field=models.CharField(default='-', max_length=255, null=True, verbose_name='Empleado:'),
        ),
        migrations.AlterField(
            model_name='messagescontactus',
            name='employee',
            field=models.CharField(default='-', max_length=255, null=True, verbose_name='Empleado:'),
        ),
        migrations.AlterField(
            model_name='messagescontactus',
            name='status',
            field=models.CharField(default='Sin ver', max_length=25, verbose_name='Estado:'),
        ),
    ]
