# Generated by Django 3.2.6 on 2022-06-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-create_at',), 'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterField(
            model_name='order',
            name='additionalInfo',
            field=models.TextField(verbose_name='Info Adicional:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dpto:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Ciudad:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=8, verbose_name='CP:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Pedido el:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Nombre:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Piso:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Apellido:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(verbose_name='Numero:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Monto:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(verbose_name='Telefono:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(max_length=255, verbose_name='Provincia:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pedido ingresado', 'Pedido ingresado'), ('Componentes reservados', 'Componentes reservados'), ('Armada', 'Armada'), ('Enviada', 'Enviada'), ('Recibida', 'Recibida')], default='Pedido ingresado', max_length=25, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Calle:'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='price',
            field=models.IntegerField(verbose_name='Precio:'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad:'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='total_price',
            field=models.IntegerField(verbose_name='Precio total:'),
        ),
    ]
