# Generated by Django 3.2.6 on 2022-06-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='inStock',
            field=models.BooleanField(default=False),
        ),
    ]
