# Generated by Django 3.2.6 on 2022-06-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_instock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-price',), 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
