# Generated by Django 3.2.6 on 2022-06-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
