# Generated by Django 3.2.6 on 2022-06-30 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Calle:')),
                ('number', models.IntegerField(verbose_name='Numero:')),
                ('flat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Piso:')),
                ('apartment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dpto:')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad:')),
                ('province', models.CharField(max_length=255, verbose_name='Provincia:')),
                ('additionalInfo', models.TextField(verbose_name='Info Adicional:')),
                ('code', models.CharField(max_length=8, verbose_name='CP:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
    ]
